version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies for node v20"
      - npm i react
      - npm i vite
      - echo "Dependencies installed"
  pre_build:
    commands:
      - echo "Install node v20"
      - npm install 
      - echo "Node v20 installed"
  build:
    commands:
      - echo "Run build"
      - npm run build
      - echo "Project built"

# artifacts:
#   base-directory: dist
#   files:
#     - '**/*'
#     - 'src/**/*'
artifacts:
  files:
    - 'dist/**/*'
    - 'src/**/*'
    - 'appspec.yml'
    - 'deploy-scripts/**/*'
  
  